version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql_notas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    container_name: spring_notas
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql_data: